config/routes.rb
BaseApp::Application.routes.draw do

  resources :mystories do
    resources :chapters
    member do
      get :publish
    end
  end

  resources :tags do
    collection do
      post :filter_tag
    end
  end

  root :to => "home#index"

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks",:registrations =>"users/registrations"}

  get "pages/index"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :users

  get "pages/not_authorized"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :mystories, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :mystory
  is_impressionable :counter_cache => true

end

app/models/create.rb
class Create < ActiveRecord::Base
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/mystory.rb
class Mystory < ActiveRecord::Base
  attachment :image, content_type: ["image/jpeg", "image/png"]
  is_impressionable :counter_cache => true
  belongs_to :user
  has_many :chapters

  has_many :tags_mystories, dependent: :destroy
  has_many :tags, through: :tags_mystories

  attr_accessor :new_tags

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base

  validate

  belongs_to :user
  belongs_to :topic

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :reply
  belongs_to :topic
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by(:name => "admin")
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tags_mystories
  has_many :mystories, through: :tags_mystories
end

app/models/tags_mystory.rb
class TagsMystory < ActiveRecord::Base
  belongs_to :mystory
  belongs_to :tag
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :cliq
  has_many :post

  belongs_to :user
  has_many :replies

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  extend FriendlyId
  friendly_id :fbname, use: :slugged

  has_one :profile
  has_and_belongs_to_many :roles
  delegate :can?, :cannot?, :to => :ability

  has_many :creates

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    data = auth['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(fbname: data['name'], uid: auth['uid'], provider: auth['provider'], :email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end

  def new_chapter_number(story)
    Chapter.where(mystory_id: story.id).count + 1
  end

  def next_chapter(story, chapter_number)
    next_chapter_number = chapter_number+1
    Chapter.where(mystory_id: story.id, number:next_chapter_number).first
  end

  def facebook_image(uid)
    "http://graph.facebook.com/#{uid}/picture"
  end

  def user_owned?
    if current_user
      current_user.id == @story.user_id
    end
  end

  def num_of_chapters(story)
    Mystory.find(story.id).chapters.count
  end

  def get_published(story)
    story.chapters.count {|chapter| chapter.published.is_true?}
  end

  def get_drafts(story)
    story.chapters.count {|chapter| chapter.published.is_false?}
  end

end

app/helpers/cliqs_helper.rb
module CliqsHelper

  def generate_cliq_history(parent_cliq)
    render 'cliqs/cliqfun', ancestors: get_cliq_ancestors(parent_cliq)
  end

  def get_cliq_ancestors(parent_cliq)
    ancestors = parent_cliq.ancestors
    ancestors << parent_cliq
    ancestors
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cliq_body/_topic_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Subject
      %th
        Interest
      %th
        Category
  %tbody
    -topics.each do |t|
      %tr
        %td
          =link_to t.subject, topic_path(t)
        %td
          =t.exp
        %td
          =generate_cliq_history(t.cliq)

app/views/layouts/admin/_main_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#baseapp-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Base Application", admin_path, :class => "navbar-brand" %>
    </div>


    <div class="collapse navbar-collapse" id="baseapp-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Users", admin_users_path) %></li>
        <li><%= link_to("Exit →", root_path) %></li>
      </ul>
    </div>

  </div>
</nav>

app/views/search/_similar_list.html.haml
%ul
  -full_ancestry(cliq).each do |desc|
    -unless desc.name == 'cliq' || desc.id.blank?
      %li
        =render "shared/cliq", desc: desc
  -if cliq.id.blank?
    %li
      =link_to '#' do
        %span.cliq-btn
          =cliq.name.capitalize

app/views/shared/_author-image.html.haml
.col-md-12.author
  .mystories-image.left
    .circleBase.facebook-image-circle
      -if story.user.provider
        = image_tag(facebook_image(story.user.uid))
      -else
        No Image
  .name.left
    ="by"
    =link_to story.user.fbname, user_path(story.user)
    %br
    ="updated at #{time_ago_in_words(story.updated_at)}"

app/views/shared/_author_image.html.haml
.col-md-12.author
  .mystories-image.left
    .circleBase.facebook-image-circle
      -if story.user.provider
        = image_tag(facebook_image(story.user.uid))
      -else
        No Image
  .name.left
    ="by"
    =link_to story.user.fbname, user_path(story.user)
    %br
    ="updated at #{time_ago_in_words(story.updated_at)}"

app/views/shared/_carrot_down.html.haml
%span.carrot-box
  %i.fa.fa-caret-right

app/views/shared/_cliq.html.haml
-if desc.ancestors.count < 2
  -bgcolor = desc.color
-else
  -bgcolor = desc.ancestors[1].color

=link_to desc.name.capitalize, cliq_path(desc), class: 'btn btn-default cliq-active',
  style: "background-color: ##{bgcolor}"

app/views/shared/_cliq_info.html.haml
-cliq ||= false
-if cliq
  %li
    =link_to "Go back: #{cliq.name.capitalize}", cliq
  %li.divider
  -cliq_latest = Cliq.cliq_latest(cliq)
  -if cliq_latest.count > 0
    -Cliq.cliq_latest(cliq).each do |latest|
      %li
        =link_to latest.name.capitalize, latest
  -else
    %li No cliq info currently

app/views/shared/_default_cliq_info.html.haml
-cliq ||= false
-if cliq
  -cliq_latest = Cliq.cliq_latest(cliq)
  -if cliq_latest.count > 0
    -Cliq.cliq_latest(cliq).each do |latest|
      %li
        =link_to latest.name.capitalize, latest
  -else
    %li No cliq info currently
-else
  %div{class:"cliq-info cliq-info-1"}
    =render "layouts/application/default_cliq_dropdown"

app/views/shared/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES * * */
  var disqus_shortname = 'writeit-beta';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.

app/views/shared/_must_sign_in.html.haml
You must have an account to access this feature