config/routes.rb
BaseApp::Application.routes.draw do

  resources :mystories do
    resources :chapters
    member do
      get :publish
    end
  end

  resources :tags do
    collection do
      post :filter_tag
    end
  end

  root :to => "home#index"

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks",:registrations =>"users/registrations"}

  get "pages/index"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :users

  get "pages/not_authorized"

end

app/models/mystory.rb
class Mystory < ActiveRecord::Base
  attachment :image, content_type: ["image/jpeg", "image/png"]
  is_impressionable :counter_cache => true
  belongs_to :user
  has_many :chapters

  has_many :tags_mystories, dependent: :destroy
  has_many :tags, through: :tags_mystories

  attr_accessor :new_tags

end

app/controllers/mystories_controller.rb
class MystoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit]
  before_action :set_story, only: [:update, :show, :edit, :publish]
  before_action :check_owner, only: [:update, :edit, :publish]
  impressionist :actions=>[:show]

  def index
    if user_signed_in?
      @stories = Mystory.where(:user_id => current_user.id)
    end
  end

  def new
    @story = Mystory.new()
    @language = Language.all
  end

  def show
    impressionist(@story, "story show")
    @chapters = Chapter.where(mystory_id: @story.id).order(:created_at)
  end

  def create
    @story = Mystory.create(mystory_params.merge(user_id: current_user.id))
    if mystory_params[:new_tags]
      create_tags(mystory_params[:new_tags])
    end
    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @language = Language.all
  end

  def update
    @story = Mystory.find(params[:id])
    if mystory_params[:new_tags]
      create_tags(mystory_params[:new_tags])
    end
    respond_to do |format|
      if @story.update(mystory_params)
        format.js {render layout: false}
        format.html { redirect_to @story, notice: 'Item was successfully updated.' }
      end
    end
  end

  private

  def set_story
    @story = Mystory.find(params[:id])
  end

  def mystory_params
    params.require(:mystory).permit(:image,:title,:description,:language,:mature, :remove_image, :new_tags, :published)
  end

  def check_owner
    unless @story.user_id == current_user.id
      # head is equivalent to a rendering
      render :status => :forbidden, :text => "You do not have access to this action"
    end
  end

  def create_tags(t)
    tags = t.split(',')
    new_tags = Array.new
    tags.each do |tag|
      name = tag.strip
      if Tag.find_by(name:name.downcase)
        new_tags << Tag.find_by(name:name.downcase)
      else
        new_tags << Tag.create(name:name.downcase)
      end
    end
    new_tags.each do |new_tag|
      TagsMystory.create(mystory_id:@story.id, tag_id:new_tag.id )
    end
  end
end

app/views/mystories/_details.html.haml
-#mystores-index (css)
.row.col-md-10.col-sm-12.col-xs-12
  .col-md-3.cover.col-sm-3.col-xs-3
    -if story.image
      =image_tag attachment_url(story, :image, :fill, 100,140)
    -else
      =image_tag('layout/nocover.png', size: "100x140")
  .col-md-9.details.col-sm-9.col-xs-9
    .row
      .default-title.col-md-12.col-sm-12
        =link_to story.title, mystory_url(story)
      .info.col-md-12.col-sm-12
        .row
          .col-md-6.col-sm-6
            .col-sm-4
              %i.fa.fa-eye
              =""
            .col-sm-4
              %i.fa.fa-star
              0
            .col-sm-4
              %i.fa.fa-comment
              0
      .published.col-md-12.col-sm-12
        .left="#{get_published(story)} Published Chapters"
        %li.tab.left
        ="#{get_drafts(story)} Drafts"
      .updated_at.col-md-12.col-sm-12
        ="Updated #{time_ago_in_words(story.updated_at)} ago"

app/views/mystories/_form.html.haml
=simple_form_for [@story] do |f|
  %div.field
    %br
    = f.error_notification
    = f.input :title
    = f.attachment_field :image
    = f.check_box :remove_image
    = f.label :remove_image
    = f.input :description, as: :text, input_html: {class:"form-control"}
    = f.input :new_tags, :input_html => { class: "tokenize" }
    = f.collection_select :language, @language, :id, :language,
      prompt: "Select a Language"
    = f.input :mature, as: :radio_buttons
  %div.actions.well
    .pull-right.top-padding-submit
      =f.submit 'Save',  class: "btn btn-default"
    .clearfix

app/views/mystories/_show_details.html.haml
-#mystories-details (css)
.row
  .col-md-5.cover.col-sm-5.col-xs-5
    -if story.image
      =image_tag attachment_url(story, :image, :fill, 180,200)
    -else
      =image_tag('layout/nocover.png', size: "180,200")
  .col-md-7.details.col-sm-7.col-xs-7
    .row
      .default-title.col-md-12.col-sm-12
        =link_to story.title, mystory_url(story)
      .info.col-md-12.col-sm-12
        .row
          .col-md-6.col-sm-6
            .col-sm-4
              %i.fa.fa-eye
              =story.impressionist_count
            .col-sm-4
              %i.fa.fa-star
              0
            .col-sm-4
              %i.fa.fa-comment
              0
      .published.col-md-12.col-sm-12
        .left="#{get_published(story)} Published Chapters"
        %li.tab.left
        ="#{get_drafts(story)} Drafts"
      .updated_at.col-md-12.col-sm-12
        ="Updated #{time_ago_in_words(story.updated_at)} ago"
      =render "shared/author_image", story:story

app/views/mystories/edit.html.haml
=render "form"

app/views/mystories/index.html.haml
.container.mystories-container
  -if @stories
    .panel
      .mystories-index
        .row
          .col-md-12.col-xs-12
            %span.pull-left
              .default-title Your Stories:
            %span.pull-right
              =link_to new_mystory_path, class: 'btn btn-default' do
                %i.fa.fa-pencil-square-o
                New Story
        .row
          .col-md-12.col-xs-12
            -@stories.each do |story|
              =render 'details', story:story
    .well
      =link_to "Create a New Story", new_mystory_path
  -else
    =render "shared/must_sign_in"

  -#-if story.published
  -#  -@publish = 'unpublish'
  -#-else
  -#  -@publish = 'publish'
  -#=simple_form_for [story], remote:true do |f|
  -#  =f.input :published, as: :hidden, :input_html => { value: !story.published }
  -#  =f.submit @publish,  class: "btn btn-default btn-xs pull-left", id:"story-#{story.id}"

app/views/mystories/new.html.haml
.well
  =render "form"

app/views/mystories/show.html.haml
.mystories-details
  =render "show_details", story:@story
.mystories-chapters
  .chapters-container
    .start-reading
      =link_to "Start Reading", mystory_chapter_path(@story, 1), class: 'btn btn-default'
    .chapters-description
      %h5=@story.description
      %ul
        -@story.tags.each do |tag|
          %li=tag.name.capitalize
-#=link_to 'back to Stories', mystories_path
-#.well
-#  %h5 Chapters
-#  %ul
-#    -@chapters.each do |chapter|
-#      %li=link_to "Chapter #{chapter.number}: #{chapter.title}", mystory_chapter_path(@story, chapter)
-#  -if user_owned?
-#    =link_to "+ Add a Chapter", new_mystory_chapter_path(@story)
-#  %h5 Tags

-#=render "shared/disqus"

app/views/mystories/update.js.erb
$(function() {
<% if @story.published? %>
    $("#story-<%=escape_javascript(@story.id.to_s)%>").html("unpublish");
<% else %>
    $("#story-<%=escape_javascript(@story.id.to_s)%>").html("publish");
<% end %>
});