config/routes.rb
BaseApp::Application.routes.draw do

  resources :mystories do
    resources :chapters
    member do
      get :publish
    end
  end

  resources :tags do
    collection do
      post :filter_tag
    end
  end

  root :to => "home#index"

  devise_for :users, controllers: {:omniauth_callbacks => "users/omniauth_callbacks",:registrations =>"users/registrations"}

  get "pages/index"
  get "/admin" => "admin/base#index", :as => "admin"

  namespace "admin" do
    resources :users
  end

  resources :users

  get "pages/not_authorized"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable

  extend FriendlyId
  friendly_id :fbname, use: :slugged

  has_one :profile
  has_and_belongs_to_many :roles
  delegate :can?, :cannot?, :to => :ability

  has_many :creates

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    data = auth['info']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create!(fbname: data['name'], uid: auth['uid'], provider: auth['provider'], :email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  helper_method :sort_column, :sort_direction, :search_params

  before_filter :find_user, :only => [:edit, :update, :show, :destroy]

  def index
    @q = User.search(params[:q])
    search_relation = @q.result
    @users = search_relation.order(sort_column + " " + sort_direction).references(:user).page params[:page]
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user].permit(:email))
      redirect_to admin_users_path, :notice => "User successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, :notice => "User deleted."
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "email"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def search_params
    { :search => params[:search] }
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    super
    current_user.update(about:params[:user][:about],
                              location:params[:user][:location],
                              website:params[:user][:website])
  end

  protected

  def user_params
    params.require(:user).permit(:about, :location, :website)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.haml
.page-header
  %h2
    Editing user #{@user.email}
= form_for [:admin, @user], :html => { :class => "form-horizontal", :role => "form" } do |f|
  = f.error_messages
  .form-group
    = f.label :email, :class => "col-sm-2 control-label"
    .col-sm-4
      = f.email_field :email, :type => :email, :class => "form-control", :placeholder => "Enter new email"
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit "Update", :class => "btn btn-default"

app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<%= search_form_for @q, :url => admin_users_path, :html => { :method => :get, :class => "well form-inline" } do |f| %>
  <div class="form-group">
    <%= f.text_field :email_cont, :type => "search", :class => "form-control", :placeholder => "Search by email" %>
  </div>

  <%= f.submit "Search", :class => "btn btn-default" %>
<% end %>

<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "id", "ID" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "created_at", "Signed up" %></th>
      <th><%= sortable "sign_in_count", "Times signed in" %></th>
      <th><%= sortable "last_sign_in_at", "Last signed in" %></th>
      <th><%= sortable "last_sign_in_ip", "Last sign in IP" %></th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="user">
        <td><%= link_to(user.id, admin_user_path(user)) %></td>
        <td><%= link_to(user.email, admin_user_path(user)) %></td>
        <td><%= l( user.created_at, :format => :short) %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= l( user.last_sign_in_at, :format => :long) %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/show.html.haml
.page-header
%h2= @user.email
%table.table.table-bordered
  %tr
    %td ID
    %td= @user.id
  %tr
    %td Email
    %td= @user.email
  %tr
    %td Sign in count
    %td= @user.sign_in_count
  %tr
    %td Last sign in at
    %td= l( @user.last_sign_in_at, :format => :long )
  %tr
    %td Last sign in IP
    %td= @user.last_sign_in_ip
  %tr
    %td Created at
    %td= l( @user.created_at, :format => :long )
  %tr
    %td Updated at
    %td= l( @user.updated_at, :format => :long )
  %tr
    %td Actions
    %td
      = link_to("Edit", edit_admin_user_path(@user), :class => "btn btn-default")
      = link_to("Destroy", admin_user_path(@user), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => "btn btn-danger btn-xs")